parameters:
#    new_mail_calendar.example.class: NewMail\CalendarBundle\Example

services:
#    new_mail_calendar.example:
#        class: %new_mail_calendar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
